### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by javiergbravo** [reactivedroid/TvFlix#18] opened 2021-02-03 18:46 UTC
**Describe the bug**
When I open the app it show different shows but the first of all shows has a black image (I guess that image did not load yet) and when I click on favourite, the application crashes.

**To Reproduce**
1. Open the app
2. Click on favourite button in first show
3. Application crashes

**Screenshot**
![Screenshot_1612376924](https://user-images.githubusercontent.com/77571676/106793861-483c5200-6658-11eb-8a9e-869d8045a9f3.png)

**Desktop (please complete the following information):**
I cloned the repository in a MacBook Pro with macOS Big Sur v11.2.

**Smartphone (please complete the following information):**
I execute in emulator Nexus 5X with API 29 (Android 10.0) and CPU/ABI  x86

**Additional context**
Logs are there:
```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.android.tvflix.dev.debug, PID: 28772
    java.lang.NullPointerException
        at com.android.tvmaze.favorite.FavoriteShowsRepository.insertShowIntoFavorites(FavoriteShowsRepository.kt:22)
        at com.android.tvmaze.home.HomeViewModel$onFavoriteClick$1.invokeSuspend(HomeViewModel.kt:83)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

It's a NullPointerException whose origin is in line 22 of FavoriteShowsRepository class on imageURL property of FavouriteShow:
```
suspend fun insertShowIntoFavorites(show: Show) {
        val favoriteShow = FavoriteShow(
            id = show.id,
            name = show.name,
            premiered = show.premiered,
            imageUrl = show.image!!["original"],
            summary = show.summary,
            rating = show.rating!!["average"],
            runtime = show.runtime!!,
            isFavorite = true
        )
        showDao.insert(favoriteShow)
 }
```

**Comment by reactivedroid** [comment] 2022-01-10 07:56
Thanks for reporting the issue. However I am not able to reproduce it. Closing the bug. Pls reopen if you find it again

**Closed by reactivedroid** 2022-01-10 07:56 UTC
